development:
  adapter: async

test:
  adapter: test

# production:
#  adapter: postgresql
#  channel_prefix: proyect_production

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: proyect_production
